FROM openjdk:9-jre

ARG SERVICE_NAME
ARG JAR_FILE

VOLUME /tmp

COPY ./build/libs/audit-service-*.jar app.jar

ENV SPRING_OUTPUT_ANSI_ENABLED=ALWAYS \
    JAVA_OPTS="" \
    SPRING_PROFILES_ACTIVE="" \
    SPRING_CLOUD_CONFIG_URI="" \
    HOST_NAME="" \
    SERVICE_NAME=${SERVICE_NAME}


LABEL APP=${SERVICE_NAME}
LABEL DOMAIN="common-service"

ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /app.jar"]

EXPOSE 8080